#define MOREEXPLOSIVES

//#define MOE_DEBUG_EXPLOSIVE
//#define MOE_DEBUG_SYNCING
//#define MOE_DEBUG_PARTICLE
//#define MOE_DEBUG_PLACEMENT
//#define MOE_DEBUG_PARTICLE
//#define MOE_DEBUG_CONFIG	
//#define MOE_DEBUG_DAMAGE